[safety-research-petri]
    [safety-research-petri.basic_info]
        name = "safety-research/petri"
        external_link = "https://github.com/safety-research/petri"
    
    [safety-research-petri.pull_request]
        history = [
            "https://github.com/safety-research/petri/pull/15",
        ]

[dvc]
    [dvc.basic_info]
        name = "iterative/dvc.org"
        external_link = "https://github.com/iterative/dvc.org"
    
    [dvc.pull_request]
        history = [
            "https://github.com/iterative/dvc.org/pull/5352",
        ]

[memgraph-card-fraud]
    [memgraph-card-fraud.basic_info]
        name = "memgraph/card-fraud"
        external_link = "https://github.com/memgraph/card-fraud"
    
    [memgraph-card-fraud.pull_request]
        history = [
            "https://github.com/memgraph/card-fraud/pull/1",
        ]

[petercat-ai-petercat]
    [petercat-ai-petercat.basic_info]
        name = "petercat-ai/petercat"
        external_link = "https://github.com/petercat-ai/petercat"
    
    [petercat-ai-petercat.pull_request]
        history = [
            "https://github.com/petercat-ai/petercat/pull/660",
        ]

[python-docs-zh-tw]
    [python-docs-zh-tw.basic_info]
        name = "python/python-docs-zh-tw"
        external_link = "https://github.com/python/python-docs-zh-tw"

    [python-docs-zh-tw.pull_request]
        history = [
            "https://github.com/python/python-docs-zh-tw/pull/609",
            "https://github.com/python/python-docs-zh-tw/pull/1139"
        ]

[ansible-documentation]
    [ansible-documentation.basic_info]
        name = "ansible/ansible-documentation"
        external_link = "https://github.com/ansible/ansible-documentation"

    [ansible-documentation.pull_request]
        history = [
            "https://github.com/ansible/ansible-documentation/pull/2062",
        ]

[kelvins-awesome-dataops]
    [kelvins-awesome-dataops.basic_info]
        name = "kelvins/awesome-dataops"
        external_link = "https://github.com/kelvins/awesome-dataops"
    
    [kelvins-awesome-dataops.pull_request]
        history = [
            "https://github.com/kelvins/awesome-dataops/pull/5",
            "https://github.com/kelvins/awesome-dataops/pull/7",
            "https://github.com/kelvins/awesome-dataops/pull/8",
        ]

[hannibal046-awesome-llm]
    [hannibal046-awesome-llm.basic_info]
        name = "Hannibal046/Awesome-LLM"
        external_link = "https://github.com/Hannibal046/Awesome-LLM"
    
    [hannibal046-awesome-llm.pull_request]
        history = [
            "https://github.com/Hannibal046/Awesome-LLM/pull/235",
        ]