[Language]
    [Language.java]
        [Language.java.info]
        level = "Beginner"
        
        [Language.java.info.image]
        text = "Java"
        fontawesome = "fa-brands fa-java"

        [Language.java.english]
        title = "Java"

        [Language.java.chinese]
        title = "Java"

    [Language.python]
        [Language.python.info]
        level = "Advanced"
        
        [Language.python.info.image]
        text = "Python"
        fontawesome = "fa-brands fa-python"

        [Language.python.english]
        title = "Python"
        # description = ["Familiar with pandas, numpy, scikit-learn, pytorch etc."]

        [Language.python.chinese]
        title = "Python"

    # [Language.julia]
    #     [Language.julia.info]
    #     level = "Beginner"
    #     fontawesome = "fa-solid fa-code"

    #     [Language.julia.english]
    #     title = "Julia"
    #     description = "<a href='https://github.com/hsiangjenli/learn-julia'>click here.</a>"

    #     [Language.julia.chinese]
    #     title = "Julia"
    #     description = "..."

    # [Language.sql]
    #     [Language.sql.info]
    #     level = "Beginner"
    #     fontawesome = "fa-solid fa-database"

    #     [Language.sql.english]
    #     title = "SQL"
    #     # description = "..."

    #     [Language.sql.chinese]
    #     title = "SQL"
    #     description = "..."

    [Language.latex]
        [Language.latex.info]
        level = "Beginner"

        [Language.latex.info.image]
        text = "LaTeX"
        fontawesome = "fa-solid fa-superscript"

        [Language.latex.english]
        title = "LaTeX"

        [Language.latex.chinese]
        title = "LaTeX"

[Website]
    # [Website.django]
    #     [Website.django.info]
    #     level = "Intermediate"
    #     fontawesome = "..."

    #     [Website.django.english]
    #     title = "Django"
    #     description = "..."

    #     [Website.django.chinese]
    #     title = "Django"
    #     description = "..."

    [Website.springboot]
        [Website.springboot.info]
        level = "Beginner"
        
        [Website.springboot.info.image]
        text = "Spring Boot"
        fontawesome = "fa-solid fa-power-off"

        [Website.springboot.english]
        title = "Spring Boot"

        [Website.springboot.chinese]
        title = "Spring Boot"

    [Website.fastapi]
        [Website.fastapi.info]
        level = "Beginner"
        
        [Website.fastapi.info.image]
        text = "FastAPI"
        fontawesome = "fa-solid fa-bolt"

        [Website.fastapi.english]
        title = "FastAPI"

        [Website.fastapi.chinese]
        title = "FastAPI"


    [Website.html]
        [Website.html.info]
        level = "Beginner"

        [Website.html.info.image]
        text = "HTML"
        fontawesome = "fa-brands fa-html5"

        [Website.html.english]
        title = "HTML"

        [Website.html.chinese]
        title = "HTML"


    [Website.CSSSCSS]
        [Website.CSSSCSS.info]
        level = "Beginner"

        [Website.CSSSCSS.info.image]
        text = "CSS/SCSS"
        fontawesome = "fa-brands fa-css3"

        [Website.CSSSCSS.english]
        title = "CSS/SCSS"

        [Website.CSSSCSS.chinese]
        title = "CSS/SCSS"


    [Website.bootstrap]
        [Website.bootstrap.info]
        level = "Beginner"

        [Website.bootstrap.info.image]
        text = "Bootstrap"
        fontawesome = "fa-brands fa-bootstrap"

        [Website.bootstrap.english]
        title = "Bootstrap"

        [Website.bootstrap.chinese]
        title = "Bootstrap"


[Tool]
    [Tool.git]
        [Tool.git.info]
        level = "Intermediate"

        [Tool.git.info.image]
        text = "git"
        fontawesome = "fa-brands fa-git-alt"

        [Tool.git.english]
        title = "git"

        [Tool.git.chinese]
        title = "git"
    

    [Tool.docker]
        [Tool.docker.info]
        level = "Intermediate"

        [Tool.docker.info.image]
        fontawesome = "fa-brands fa-docker"

        [Tool.docker.english]
        title = "Docker"

        [Tool.docker.chinese]
        title = "Docker"


    # [Tool.spark]
    #     [Tool.spark.info]
    #     level = "Ongoing"
    #     fontawesome = "..."

    #     [Tool.spark.english]
    #     title = "Spark"
    #     description = "..."

    #     [Tool.spark.chinese]
    #     title = "Spark"
    #     description = "..."
    

    # [Tool.hadoop]
    #     [Tool.hadoop.info]
    #     level = "Ongoing"
    #     fontawesome = "..."

    #     [Tool.hadoop.english]
    #     title = "Hadoop"
    #     description = "..."

    #     [Tool.hadoop.chinese]
    #     title = "Hadoop"
    #     description = "..."
["CI/CD"]
    ["CI/CD".githubActions]
        ["CI/CD".githubActions.info]
        level = "Beginner"

    # ["CI/CD".k8s]
    #     ["CI/CD".k8s.info]
    #     level = "Beginner"

    #     ["CI/CD".k8s.info.image]
    #     text = "Kubernetes (k8s)"
    #     fontawesome = "fa-solid fa-dharmachakra"

    #     ["CI/CD".k8s.english]
    #     title = "Kubernetes (k8s)"
    #     description = [
    #         "Familiar with using k3s to operate kubectl commands, including deployment and management.",
    #         "k3s is a lightweight version of Kubernetes (k8s), fully compatible with kubectl.",
    #     ]

    #     ["CI/CD".k8s.chinese]
    #     title = "Kubernetes (k8s)"
    #     description = [
    #         "熟悉使用 k3s 執行 kubectl 指令，包含部署與管理。",
    #         "k3s 是 Kubernetes (k8s) 的輕量版，指令相容。",
    #     ]

    ["CI/CD".azureDevOps]
        ["CI/CD".azureDevOps.info]
        level = "Beginner"

        ["CI/CD".azureDevOps.info.image]
        text = "Azure DevOps"
        fontawesome = "fa-brands fa-microsoft"

        ["CI/CD".azureDevOps.english]
        title = "Azure DevOps"
        # description = ["Familiar with setting up personal Agent on Azure DevOps."]

        ["CI/CD".azureDevOps.chinese]
        title = "Azure DevOps"
        description = ["能夠在 Azure DevOps 上建立個人 Agent。"]

        ["CI/CD".githubActions.info.image]
        text = "Github Actions"
        fontawesome = "fa-solid fa-code-compare"

        ["CI/CD".githubActions.english]
        title = "Github Actions"

        ["CI/CD".githubActions.chinese]
        title = "Github Actions"
    
    ["CI/CD".MLflow]
        ["CI/CD".MLflow.info]
        level = "Beginner"

        ["CI/CD".MLflow.info.image]
        text = "MLflow"
        fontawesome = "fa-solid fa-gauge-high"

        ["CI/CD".MLflow.english]
        title = "MLflow"
        # description = ["Using MLflow to track experiments and mointor the hardware usage."]

        ["CI/CD".MLflow.chinese]
        title = "MLflow"
    
    # ["CI/CD".Terraform]
    #     ["CI/CD".Terraform.info]
    #     level = "Beginner"
    #     fontawesome = "fa-solid fa-industry"

    #     ["CI/CD".Terraform.english]
    #     title = "Terraform"
    #     description = [
    #         # S, Too many docker images need to be built and pushed to the docker hub.
    #         # T, Organize the docker images and ....
    #         # A, How to do....
    #         # R, Now I can use Terraform to automate rebuilding the docker images when the code is updated.
    #     ]

        # ["CI/CD".Terraform.chinese]
        # title = "Terraform"
        # description = "..."

    ["CI/CD".GitOps]
        ["CI/CD".GitOps.info]
        level = "Beginner"

        ["CI/CD".GitOps.info.image]
        text = "GitOps"
        fontawesome = "fa-solid fa-code-branch"

        ["CI/CD".GitOps.english]
        title = "GitOps"

        ["CI/CD".GitOps.chinese]
        title = "GitOps"

    # ["CI/CD".Ansible]
    #     ["CI/CD".Ansible.info]
    #     level = "Beginner"

    #     ["CI/CD".Ansible.info.image]
    #     text = "Ansible"
    #     fontawesome = "fa-solid fa-a"

    #     ["CI/CD".Ansible.english]
    #     title = "Ansible"

    #     ["CI/CD".Ansible.chinese]
    #     title = "Ansible"

[Platform]
    [Platform.ubuntu]
        [Platform.ubuntu.info]
        level = "Intermediate"

        [Platform.ubuntu.info.image]
        text = "Ubuntu"
        fontawesome = "fa-brands fa-ubuntu"

        [Platform.ubuntu.english]
        title = "Ubuntu"

        [Platform.ubuntu.chinese]
        title = "Ubuntu"
    
    [Platform.mac_os]
        [Platform.mac_os.info]
        level = "Intermediate"

        [Platform.mac_os.info.image]
        text = "mac OS"
        fontawesome = "fa-brands fa-apple"

        [Platform.mac_os.english]
        title = "mac OS"

        [Platform.mac_os.chinese]
        title = "mac OS"
    

    [Platform.windows]
        [Platform.windows.info]
        level = "Intermediate"

        [Platform.windows.info.image]
        text = "Windows"
        fontawesome = "fa-brands fa-windows"

        [Platform.windows.english]
        title = "Windows"

        [Platform.windows.chinese]
        title = "Windows"

